### ISSUE TITLE
Less claustrophobic clipart experience

### ISSUE THREAD

**Issue by TWiStErRob** [romannurik/AndroidAssetStudio#93]
Given the amount of icons and the amount of scrolling needed to go through the list I think the clipart UI should be updated a little. I played a little with the page and with 3 simple changes I was able to achieve this:
![image](https://cloud.githubusercontent.com/assets/2906988/13572829/a780748e-e47c-11e5-8212-5d09869dd5fc.png)

I moved `canvas.form-image-preview` into `<label for="_frm-iconform-source">` and updated these CSS styles:

``` css
.form-image-preview {
    /* max-height: 135px; */
    max-width: 135px;
    margin-top: 20px;
}
.form-image-clipart-list {
    width: 570px;
    height: 250px;
}
```

To see in context why I opened this issue, consider a wider-than-your-body sized monitor (#firstworldproblems):
![image](https://cloud.githubusercontent.com/assets/2906988/13572964/5e0bbc5e-e47d-11e5-9b49-1a57286be977.png)
